spring:  #redis 配置(集群模式)
  redis:
    # Redis数据库索引（默认为0）,如果设置为1，那么存入的key-value都存放在select 1中
    database: 0
    # Redis服务器地址
    # Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 1
    # 连接超时时间（毫秒）
    timeout: 100000ms
    # 集群
    cluster:
      nodes:
        - 10.2.111.171:22400
        - 10.2.111.178:22400
        - 10.2.111.181:22400
        - 10.2.111.182:22400
      max-redirects: 3


datasource:
  sources:
    ###第一个库
    first:
      url: jdbc:oracle:thin:@//10.2.25.192:1521/orcl
      username: ehl_gs
      password: ehl1234
    ###第二个库
    second:
      url: jdbc:oracle:thin:@//10.2.25.192:1521/orcl
      username: ehl_gs
      password: ehl1234
