###################  容器相关设置  ###################
server:
  #发布端口
  port: 8764
  tomcat:
    uri-encoding: UTF-8
    # 如果是采用WAR包的方式部署，请修改容器对应的配置项，如Tomcat，见以下 max-http-header-size 项注释
    max-http-post-size: 8MB
  servlet:
    context-path: /koms-is
  # 如果是采用WAR包的方式部署，请修改容器对应的配置项
  # 如Tomcat：
  #  <Connector port="8080" protocol="HTTP/1.1"
  #  connectionTimeout="20000"
  #  redirectPort="8443" maxHttpHeaderSize="65536" maxPostSize="4194304"
  #  URIEncoding="UTF-8"/>
  max-http-header-size: 32KB

###################  注册服务配置  ###################
eureka:
  instance:
    health-check-url-path: ${server.servlet.context-path}/health
    status-page-url-path: ${server.servlet.context-path}/login
  client:
    serviceUrl:
      #注册服务地址
      defaultZone: http://localhost:8081/eureka/

###################  spring配置  ###################
spring:
  ###环境配置，目前可选值为prod和dev，生产环境需配置为prod
  profiles:
    active: dev
  application:
    #注册服务名称
    name: komsis
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  messages:
    encoding: UTF-8
  mvc:
    view:
      prefix: /templates
      suffix: .html


management:
  security:
    enabled: false
  health:
    redis:
      enabled: false
    elasticsearch:
      enabled: false
  #    rabbit:
  #      enabled: false
  endpoints:
    web:
      exposure:
        include: bus-refresh

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/prepared/pProject/mapper/*.xml
  typeAliasesPackage: com.prepared.pProject.entity
  global-config:
    ###0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    id-type: 0
    db-column-underline: false
    refresh-mapper: true
    ###Oracle主键生成器
    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
  configuration:
    map-underscore-to-camel-case: true
    ###配置的缓存的全局开关（true/false）
    cache-enabled: true
    ###延时加载的开关（true/false）
    lazyLoadingEnabled: true
    ###开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性（true/false）
    multipleResultSetsEnabled: true
    ###打印sql语句,调试用
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

###################  属性加密配置  ###################
jasypt:
  encryptor:
    property:
      prefix: "ENC@["
      suffix: "]"

