server:
  port: 8081
  ip: localhost

spring:
  application:
    name: erueka-server

eureka:
  client:
    # 不注册自身
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${server.ip}:${server.port}/eureka

